spring:
  data:
    redis:
      host: redis
      port: 6379

aws:
  endpoint-override: http://localstack:4566
  dynamodb:
    endpoint: http://localstack:4566
  sqs:
    endpoint: http://localstack:4566

logging:
  level:
    root: INFO
    com.eventticket: DEBUG
    org.springframework.web: DEBUG
    software.amazon.awssdk: DEBUG
    software.amazon.awssdk.services.sqs: DEBUG
    software.amazon.awssdk.services.dynamodb: DEBUG
