spring:
  data:
    redis:
      host: redis
      port: 6379

aws:
  endpoint-override: http://localstack:4566
  dynamodb:
    endpoint: http://localstack:4566
  sqs:
    endpoint: http://localstack:4566

logging:
  level:
    root: INFO
    com.eventticket: INFO
    org.springframework.web: INFO
